//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookmobile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outreach
    {
        public int OutreachId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int SchoolId { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public int StaffIdPrimary { get; set; }
        public Nullable<int> StaffIdSecondary { get; set; }
        public string Notes { get; set; }
    
        public virtual LibraryStaff LibraryStaff { get; set; }
        public virtual School School { get; set; }
    }
}
